### ISSUE TITLE
"mode" in new has to be i32

### ISSUE THREAD

**Issue by ioncodes** [tathanhdinh/keystone-rs#1]
Hey! Thanks for this binding! I tried to compile and I faced 2 issues. The first one was due to bingen, it doesn't support stable rustfmt, only nightly. Just letting you know. The second issue is that keystone-rs expects "mode" to be an i32 not u32. I applied that fix on my [fork](https://github.com/ioncodes/keystone-rs/commit/54474fae712e2873a0aa163ac60a3a25147c31ab#diff-b4aea3e418ccdb71239b96952d9cddb6R77) and it compiles now! Everything works as expected!

**Comment by tathanhdinh** [comment]
Many thanks @ioncodes 
For the second issue, the underlying for `ks_mode` (generated by bindgen) on your machine is `u32`? (do you test it on Windows or Linux?). Because in my machine (running Windows 7), it is `i32`.

I have faced a similar problem when `bindgen` (when running on Windows and Linux) generates two different underlying types for `enum`.

**Comment by ioncodes** [comment]
I will try it out on Linux and Window as soon as I get home. I tried it out on my Mac.

**Comment by ioncodes** [comment]
I'll test out the fix (https://github.com/tathanhdinh/keystone-rs/commit/f173f94d02d6c13f47c3279ab57106af3fd52699) as soon as I get up!

**Comment by tathanhdinh** [comment]
@ioncodes Please check out the [new binding](https://github.com/tathanhdinh/keystone-rs/tree/new_build_system), it should fix the bug :)

**Comment by ioncodes** [comment]
Works perfectly! Thanks!
